respuesta = ('{\n'
 '   "results" : [\n'
 '      {\n'
 '         "address_components" : [\n'
 '            {\n'
 '               "long_name" : "52",\n'
 '               "short_name" : "52",\n'
 '               "types" : [ "street_number" ]\n'
 '            },\n'
 '            {\n'
 '               "long_name" : "San Lorenzo",\n'
 '               "short_name" : "San Lorenzo",\n'
 '               "types" : [ "route" ]\n'
 '            },\n'
 '            {\n'
 '               "long_name" : "Gaiman",\n'
 '               "short_name" : "Gaiman",\n'
 '               "types" : [ "locality", "political" ]\n'
 '            },\n'
 '            {\n'
 '               "long_name" : "Gaiman",\n'
 '               "short_name" : "Gaiman",\n'
 '               "types" : [ "administrative_area_level_2", "political" ]\n'
 '            },\n'
 '            {\n'
 '               "long_name" : "Chubut",\n'
 '               "short_name" : "Chubut",\n'
 '               "types" : [ "administrative_area_level_1", "political" ]\n'
 '            },\n'
 '            {\n'
 '               "long_name" : "Argentina",\n'
 '               "short_name" : "AR",\n'
 '               "types" : [ "country", "political" ]\n'
 '            }\n'
 '         ],\n'
 '         "formatted_address" : "San Lorenzo 52, Gaiman, Chubut, Argentina",\n'
 '         "geometry" : {\n'
 '            "location" : {\n'
 '               "lat" : -43.2858637,\n'
 '               "lng" : -65.5086913\n'
 '            },\n'
 '            "location_type" : "RANGE_INTERPOLATED",\n'
 '            "viewport" : {\n'
 '               "northeast" : {\n'
 '                  "lat" : -43.2845147197085,\n'
 '                  "lng" : -65.50734231970848\n'
 '               },\n'
 '               "southwest" : {\n'
 '                  "lat" : -43.2872126802915,\n'
 '                  "lng" : -65.51004028029149\n'
 '               }\n'
 '            }\n'
 '         },\n'
 '         "partial_match" : true,\n'
 '         "place_id" : '
 '"EilTYW4gTG9yZW56byA1MiwgR2FpbWFuLCBDaHVidXQsIEFyZ2VudGluYSIwEi4KFAoSCd3KypeuOAG-EavRJmA2JAMwEDQqFAoSCT_d8lWpOAG-EQSNWGykYtkn",\n'
 '         "types" : [ "street_address" ]\n'
 '      }\n'
 '   ],\n'
 '   "status" : "OK"\n'
 '}\n')
